### PR TITLE
Recursive shape from model

### PR DESCRIPTION
**Pull request by massimo-nocentini**
# Rationale

The upcoming commits allow us to select a shape recursively among a nested composition. It also factors the message sends for equality check that decides when to stop the lookup.

Because a `RSComposite` is a `RSShape` subclass, its instances can hold a model as well, and that property is taken into account by the proposed changes. If a composite has a model, then the behavior doesn't change; on the contrary, it forwards the messages to its enclosing shapes to continue the search recursively. The recursion stops in `RSShape` objects that can invoke the selecting block passed around during the process.

This PR is a consequence of a talk with @pavel-krivanek. 

# Use cases

The need for selecting a shape nested in a composite born from the sake of providing a slots-oriented representation of an object. For instance, the `ValueLink` object `(4 ~~> (3 ~~> (2 ~~> nil)))` can be visualised as
vl
whose `nextLink` slot points to the unfolded representation
vls
The proposed changes allow us 
- to select the `RSBox` shape corresponding to `nextLink` slots and
- to start edges from there even when those boxes are in an enclosing composite.

The last example that we report is the slot-oriented visualisation of a `BinomialHeap` built by inserting the first `50` naturals and then popping 5 of them consecutively,
bt
that usually can be represented by the more compact (but less explicit) representation
btu

### CODE REVIEW

**Comment by akevalion** [comment]
Maybe we can check this pull request @bergel

**Comment by akevalion** [comment]
Hi @massimo-nocentini I have tried your code, but: 

- There is a conflict with RSGroup>> #shapeFromModel:
- There are not tests or examples
- `shapeFromModel:using:` and: shapesFromModel:using:` protocol is `As yet unclassified`.

Could you please review and fix these issues?

**Comment by massimo-nocentini** [comment]
Hi @akevalion , I've pushed some commits with the fixes you requested.

Btw, I've looked at the message `#deepShapeFromModel:`, do you think that both implementation could be unified? I'm asking because the implementation of that selector in `RSTContainer` sends `#shapeFromModel:`.

Thanks for the attention, let me know if you need some more changes.

**Comment by akevalion** [comment]
We will considere it later, because we need more tests and documentation.

**Pull request closed without merging**
