### PR TITLE
Roassal3 svg

### LINKED ISSUE #213: Athens-SVG has to be revisited
From Pavel (https://discordapp.com/channels/223421264751099906/300020095844089856/706784451157426176)

I have created the GitHub repository for Athens-SVG so it is no more needed to load it from Smalltalkhub: https://github.com/pharo-contributions/Athens-SVG

I only want to notice that it is dependent on XML-Parser
the Baseline of Roassal 3 ignores it
(and right now, the baseline of AthensSVG does not express this dependency too)
for integration of Roassal3 into Pharo, the dependency on this package should be cleaned (or XML-Parser will need to be in Pharo, which I do not know if we want)
I committed Athens-SVG version with improved arc rendering so it is not able to display correctly more files

### PR DESCRIPTION
**Pull request by pavel-krivanek**
add Roassal3-SVG package dependent on Athens-SVG. Currently, loaded by default.

fixes #213

### CODE REVIEW

**Comment by akevalion** [comment]
did you rename Roassal3-Shapes to Roassal3-SVG?

also this PR is red

**Comment by pavel-krivanek** [comment]
No, I added Roassal3-SVG package and moved two line classes (with dependants) there

**Comment by pavel-krivanek** [comment]
The failure is only a network issue for one sub-task

**Comment by akevalion** [comment]
Some example like `example07Phyco` now are extentions on `Roassal3-SVG` This means that `Roassal3-SVG` depends on `Roassal3-Examples-Basic`.

Then if I load for example 
```Smalltalk
Metacello new
    baseline: 'Roassal3';
    repository: 'github://ObjectProfile/Roassal3';
    load: 'SVG'
```
should fall because `SVG` group does not includes group `Examples`.

I think that `SVG` group should be include in group `Core`.
Let me know what you think

**Comment by pavel-krivanek** [comment]
I think that we should introduce `Roassal3-SVG-Tests` package. The SVG support should not be in core group because of huge dependencies it creates

**Comment by akevalion** [comment]
Roassal uses these 3 classes  
RSSVGPath, RSSVGPathLine and RSBimetricLine. 
And I think RSSVGPath, RSSVGPathLine are like core classes for Roassal3

**Comment by pavel-krivanek** [comment]
I created Roassal3-SVG-Tests and Roassal3-SVG-Examples. These classes are important but keep in mind that for integration to Pharo, the dependencies need to be kept small. If SVG support can be detached then it should be optional.

**Comment by bergel** [comment]
We accepted this PR. Thanks Pavel! This is a valuable contribution!

**Pull request merged**
