### PR TITLE
Some Cleanups (tags, categories)

### LINKED ISSUE #400: Some Cleanups (tags, categories)
Some cleanups in alignment with what was done also in the base image to provide more consistency for class categorization and method categories

For instance fix uncategorized classes (either into a specific class category or by using "Base" for the base functionality within a package)

### PR DESCRIPTION
**Pull request by astares**
Fix #400

### CODE REVIEW

**Comment by astares** [comment]
@akevalion or @bergel: Are you able to review?

**Comment by akevalion** [comment]
It looks good for me

**Comment by astares** [comment]
@akevalion 
Thanks!

**Comment by astares** [comment]
@akevalion can we update the standard Pharo 9 image with this (and other fixes)

**Comment by akevalion** [comment]
I will create a new pr to pharo

**Pull request merged**
