### PR TITLE
Using RSTLine trait in RSAbstract marker

### PR DESCRIPTION
**Pull request by jordanmontt**
Using this trait enables the use of useful methods, like width: paint: marker: ... etc

### CODE REVIEW

**Comment by akevalion** [comment]
Could you please add a test

**Comment by akevalion** [comment]
The test can be related to the functionality of the RSTLine in a sub class of `RSAbstractChartDecoration `

**Comment by jordanmontt** [comment]
I added some tests. Can you have a look please?

**Comment by akevalion** [comment]
Yes, I like the tests

**Pull request merged**
