### PR TITLE
Add in Boxplot

### PR DESCRIPTION
**Pull request by ctSkennerton**
This pull request adds in `RSBoxPlot` to the Roassal3-Chart package. The interface is similar to the `boxplot` function in matplotlib which takes a 2D dataset as the input. The main implementation detail is that I haven't defined a `quantile:` method in the class, instead I'm relying on the collection to know how to respond to that message. Currently `quantile:` is implemented in PolyMath as an extension for a `SortedCollection`. If it's preferable, I can reimplement it in the box plot class.

### CODE REVIEW

**Comment by ctSkennerton** [comment]
I can see the failing tests are because the quantile message isn't understood. I'm happy to go either way to either add polymath to the baseline or if you prefer not to add in the dependency to implement quantile within the box plot class.

**Comment by akevalion** [comment]
Hi @ctSkennerton Roassal3 can not depend on PolyMath, maybe we can use `rsQuantile:` as a extension method in roassal3 boxplot

**Comment by ctSkennerton** [comment]
@akevalion thanks for the guidance. I've updated the class to use an internal implementation of quantile.

**Comment by akevalion** [comment]
Hi @ctSkennerton, it works nice!

**Pull request merged**
