### PR TITLE
Continue the Roassal3 renamings

### PR DESCRIPTION
**Pull request by NourDjihan**
This PR touches these classes:
- RSPopupDecoration => RSChartPopupDecoration

- RSEasing + RSEasingTest => Interpolator

Adding the Builder suffix in:
- RSPie
- RSForceLayoutInSpaces
- RSLegend
- RSChart

- RSAbstractChartElement => RSAbstractChartPlot

Layout instead of strategy in:
- RSSunburstConstantWidthStrategy
- RSSunburstExtentLayout

### CODE REVIEW

**Comment by akevalion** [comment]
There are conflicts with this pull request

**Comment by NourDjihan** [comment]
Added to my todo list to fix.

**Comment by akevalion** [comment]
This pr has conflicts with the last version of roassl3

**Comment by akevalion** [comment]
I will close this pr and I will apply your changes manually

**Comment by akevalion** [comment]
I have included your changes in roassal3 manually

**Comment by NourDjihan** [comment]
Noted. Thank you for the feedback.

**Pull request closed without merging**
